version: "3.9"

services:
  pg:
    image: postgres
    environment:
    - POSTGRES_USER=user
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=golang
    ports:
    - 5432:5432
    volumes:
    - data-vol:/var/lib/postgresql/data

  golang-start:
    build: .
    ports:
    - 8080:8080
    environment:
      DSN: "host=pg user=user password=password dbname=golang port=5432"
    restart: always
    depends_on:
    - pg

volumes:
  data-vol: