apiVersion: v1
kind: Service
metadata:
  name: goapp-service
  labels:
    app: goapp
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 32000
  selector:
    app: goapp